- name: Prepare
  hosts: all
  gather_facts: yes
  tasks:
    - name: debug task
      debug:
         msg: "to jest: {{ ansible_facts['distribution'] }}"

    - name: install sudo
      package:
        name: sudo
        state: present

    - name: install python3
      package:
        name: python3
        state: present
